{{- if .Values.backup.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name : {{ include "vaultwarden.fullname" . }}-rclone
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: vaultwarden
data:
  rclone.conf: |
{{ (.Files.Get .Values.backup.config | indent 4 )}}
{{- end }}